server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8282}

spring:
  application:
    name: authservice

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    continue-on-error: true
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: embedded
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false


# CORS placeholder (used by a CorsConfiguration bean later)
app:
  api:
    base-path: /api
  cors:
    allowed-origins:
      - http://localhost:4201
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
    allow-credentials: true
  jwt:
    access-token-seconds: 3600
    refresh-token-days: 14            # 14 days refresh lifetime
  cookie:
    refresh:
      name: REFRESH_TOKEN
      #domain: localhost               # set your domain in prod (e.g., app.example.com)
      path: /api/auth
      secure: false                   # true in prod (HTTPS)
      http-only: true
      same-site: Lax                  # use "None" for cross-site; requires secure=true
  security:
      issuer: ${AUTH_ISSUER:http://localhost:8282}
      access-token-seconds: ${ACCESS_TOKEN_SECONDS:3600}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  security:
    enabled: false

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG
        security:
          authentication: DEBUG
      zalando:
        logbook: INFO